# Generated by Django 4.0 on 2023-01-04 23:54

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True)),
                ('documentation', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True)),
                ('deployed', models.URLField(blank=True, null=True)),
                ('repository', models.URLField(blank=True, null=True)),
                ('video_presentation', models.URLField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('co_creators', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('showpiece_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('languages', models.ManyToManyField(blank=True, related_name='project', to='projects.Language')),
            ],
        ),
    ]
